### ISSUE TITLE
Number of terminals might be wrong, when startFrom is used

### ISSUE THREAD

**Issue by eivanov89** [yugabyte/tpcc#141]
Hi folks,

[Here](https://github.com/yugabyte/tpcc/blob/fe07ceb48c25de5dbc64cb30d5044f52f292df22/src/com/oltpbenchmark/api/BenchmarkModule.java#L354) you seem to want comparing agains `numWarehouses + workConf.getStartWarehouseIdForShard() - 1`.

**Comment by sonalsagarwal** [comment]
This part of code seems to be redundant, as we are computing and setting the value for upperTerminalId just before this 'if' condition.

**Comment by hbhanawat** [comment]
Closing as per the comment above.
